name: Publish

on:
  release:
    types: [published]

jobs:
  npm:
    name: NPM
    runs-on: ubuntu-latest
    environment: NPM Release Publishing
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - run: corepack enable pnpm

      - uses: actions/setup-node@ca2d4e0cdd8c63d9ebfedc3d16d450a870caf31c
        with:
          node-version-file: ".nvmrc"
          cache: pnpm

      - uses: actions/github-script@e3cbab99d3a9b271e1b79fc96d103a4a5534998c
        id: version
        with:
          script: |
            const semver = context.ref.replace('refs/tags/v', '')
            if (semver.match(/^[0-9]+\.[0-9]+\.[0-9]+$/)){
              return semver
            }
            throw new Error('not semver')
          result-encoding: string

      - run: pnpm install --frozen-lockfile
      - run: pnpm build

      - name: Version
        run: |
          node ./scripts/version.js --version ${{ steps.version.outputs.result }}
      - name: Publish
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
          npm run publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
